const { SlashCommandSubcommandBuilder, PermissionsBitField } = require('discord.js');
const { updateServerConfig } = require('../../utils/server/updateServerConfig');
const { serverColumnNames } = require('../../db/init');
const { getServerConfig } = require('../../utils/server/getServerConfig');
const { messages } = require('../../messages.json');
const ContainerMessage = require('../../utils/classes/ContainerMessage');

module.exports = {
    data: new SlashCommandSubcommandBuilder()
        .setName('load')
        .setDescription("Loads a config made in the dashboard")
        .addStringOption(option => option.setName('key').setDescription('The one-time key generated by the dashboard').setRequired(true)),
    async execute(interaction) {
        if (!interaction.member.permissions.has(PermissionsBitField.Flags.Administrator)) return interaction.reply(new ContainerMessage(messages.errors.MISSING_PERMISSION.replaceAll('{permission}', 'administrator')).isEphemeral().build());

        const key = interaction.options.getString('key');

        const response = await fetch(`https://api.leveling.workers.dev/loadconfig`, {
            method: "POST",
            body: JSON.stringify({
                configKey: key,
                serverId: interaction.guild.id,
                apiSecret: process.env.LOAD_CONFIG_SECRET
            }),
            headers: { 'Content-Type': 'application/json' }
        });

        if (!response.ok) return interaction.reply(new ContainerMessage(messages.errors.LOAD_CONFIG.build()).isEphemeral().build());

        const data = await response.json();
        const newConfig = data.config;

        const currentConfig = await getServerConfig(interaction.guild.id);

        let changes = [];

        for (const [key, newValue] of Object.entries(newConfig)) {
            if (!serverColumnNames.includes(key)) continue;

            const currentValue = currentConfig[key]?.value;
            if (currentValue !== newValue) {
                await updateServerConfig(interaction.guild.id, key, newValue);
                changes.push(`${key}: ${newValue}`);
            }
        }

        if (!changes.length) return interaction.reply(new ContainerMessage(messages.errors.SAME_CONFIG.build()).isEphemeral().build());

        await interaction.reply(new ContainerMessage(messages.success.UPDATE_CONFIG_VALUE.replaceAll('{config}', 'Dashboard Config').replaceAll('{value}', changes.join(', '))).build());
    }
};